### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished when executing scenario

### ISSUE THREAD

**Issue by dkmdnielsen** [cucumber/cucumber#825] opened 2015-04-01 13:44 UTC
From http://stackoverflow.com/questions/29300312/cucumber-activerecordconnectionnotestablished

I am getting an exception "ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base". I am really on the deep end of the pool (no pun intended) with this one. I really don't understand the connection and connection pool handling, even as much as I have studied this problem. I'm assuming this might be scope related inside of Cucumber, but I do not know. Any and all assistance is appreciated.

Here are the details:

The exception occurs when I perform a count from a Then clause:
```ruby
WorkTable.where('? is not null',col['COLUMN_NAME']).count
```
It does not occur if I send the sql directly through the connection:
```ruby
WorkTable.connection.select_all(st.encode('utf-8')).first['nulls']
```
My scenario reads as follows:
```cucumber
  Scenario: CompanyMaster test for null value
    Given table dbo.base_table in stage
    Then these columns are expected to be not null
      | COLUMN_NAME                         | nulls |
      | id                                  | 0 |
      | company_name                        | 0 |
```
I establish my class in my env.rb:
```ruby
class WorkTable < ActiveRecord::Base
end

ActiveRecord::Base.configurations = YAML.load_file(yaml)  # yaml is database.yml file name
```
I establish my connection in a Given clause, extracting the environment I want to connect to from the Given statement (env variable):
```ruby
Given(/^table (\w+)\.?([\w_]+) in (\w+)(?: as (\w+))?$/) do |schema,name,env,id|
  @sc_name = schema_file_name(schema,name)
  WorkTable.logger.info title_line("* Active table(#{@sc_name}) *")
  case id
    #  ActiveRecord::Base.configurations[env]
    ...
    else
      WorkTable.table_name = @sc_name
      WorkTable.establish_connection(env.to_sym)
      # ary = get_tables(WorkTable,schema:schema)
      # expect( ary.any?{|s| s.casecmp(name)==0 } ).to eq(true)
  end
end
```
I execute my test in a Then clause:
```ruby
Then(/^these columns are expected to be not null$/) do |columns|
  # expected is an instance of Cucumber::Ast::Table
  WorkTable.logger.info title_line('Columns cannot be null')

  results = []
  columns.hashes.each {|col|
    results << {
        'COLUMN_NAME' => col['COLUMN_NAME'],
        'nulls' => WorkTable.where('? is not null',col['COLUMN_NAME']).count.to_s
    }
  }
  columns.diff!(results,surplus_row: false)
end
```
It is the WorkTable.where that throws the "ActiveRecord::ConnectionNotEstablished: No connection pool for ActiveRecord::Base". Again, if I use the WorkTable.connection method, I do not get it. Also, it executes fine if I copy all the functional code to single ruby script.

I see the following when I "pp WorkTable.connection":
```
#<ActiveRecord::ConnectionAdapters::SQLServerAdapter version: 4.2.2, mode: dblib, azure: false>
```
And I see the following when I "pp WorkTable.connection_pool":
```
#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x42f5238
 @automatic_reconnect=true,
 @available=
  #<ActiveRecord::ConnectionAdapters::ConnectionPool::Queue:0x42f4f20
   @cond=
    #<MonitorMixin::ConditionVariable:0x42f4ed8
     @cond=
      #<ConditionVariable:0x42f4de8
       @waiters=[],
       @waiters_mutex=#<Mutex:0x42f4d58>>,
     @monitor=
      #<ActiveRecord::ConnectionAdapters::ConnectionPool:0x42f5238 ...>>,
   @lock=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x42f5238 ...>,
   @num_waiting=0,
   @queue=[]>,
 @checkout_timeout=5,
 @connections=
  [#<ActiveRecord::ConnectionAdapters::SQLServerAdapter version: 4.2.2, mode: dblib, azure: false>],
 @mon_count=0,
 @mon_mutex=#<Mutex:0x42f51c0>,
 @mon_owner=nil,
 @reaper=
  #<ActiveRecord::ConnectionAdapters::ConnectionPool::Reaper:0x42f51a8
   @frequency=nil,
   @pool=#<ActiveRecord::ConnectionAdapters::ConnectionPool:0x42f5238 ...>>,
 @reserved_connections=
  #<ThreadSafe::Cache:0x42f4fc8
   @backend=
    {16931712=>
      #<ActiveRecord::ConnectionAdapters::SQLServerAdapter version: 4.2.2, mode: dblib, azure: false>},
   @default_proc=nil>,
 @size=5,
 @spec=
  #<ActiveRecord::ConnectionAdapters::ConnectionSpecification:0x42f55c8
   @adapter_method="sqlserver_connection",
   @config=
    {:host=>"server_name",
     :database=>"mssb_stg",
     :encoding=>"utf-8",
     :adapter=>"sqlserver",
     :timeout=>5000}>>
```
Ruby 1.9.3, activerecord (4.2.0), activerecord-sqlserver-adapter (4.2.2), and cucumber (1.3.18). And sql server 2014 [this has been a bugger for me].

**==Additional detail ==**

I thought this might be a SqlServer 2014 related problem, as I am having a number of issues with it.  However, I get the same exception when I reconfigure the setup to work with SqLite. So it is not related to db platform.

Thank you for you time and consideration.  I thought I posted this here earlier when I did on on StackOverflow.  But I do not see it in the list.

Any clues?  I'm going to start a whole new project an work it up piece by piece to see exactly where the problem begins.  The project I have now is fairly involved.

Thanks again,
dvn

**Comment by mattwynne** [comment] 2015-04-01 15:59
Hi @dkmdnielsen, thanks for getting in touch.

Sorry to hear you're having trouble with this.

We try to keep this issue tracker for bugs and features, not support, since notifications are only sent to the developers. You'll get a much wider audience for help if you post on the [community forum](http://cukes.info/support#forum).

I'm going to close this ticket as this is unlikely to be caused by a bug in Cucumber, but do please re-open it if that turns out to be the case.

Just as a general piece of advice, I think that trying to create a small representative repo is a great idea. It will not only help others to diagnose the problem, but it might also give you some clues to help you isolate what the issues are.

**Closed by mattwynne** 2015-04-01 15:59 UTC
