### ISSUE TITLE
tags applied incorrectly

### ISSUE THREAD

**Issue by CamJN** [cucumber/cucumber#787] opened 2014-12-30 19:31 UTC
I have two feature files with a total of three scenarios, with a `@javascript` tag on only one scenario.
Calling cucumber with no flags treats all scenarios like they have a `@javascript` tag, yet calling cucumber as `cucumber --tags @javascript` only runs the one scenario.

**Comment by mattwynne** [comment] 2015-01-01 08:19
@CamJN the behaviour @aslakhellesoy describes is what I'd expect to happen.

I think the problem you've described is that the features run as though every scenario were tagged with `@javascript` - am I right?

It sounds like there's a bug somewhere in the layers of Cucumber / Cucumber-Rails / Capybara / Selenium WebDriver, but probably not in Cucumber. I'll close this ticket, but I'm sure the users and maintainers of those tools will appreciate it if you can narrow down what the problem is.

Another thing to try would be upgrading all your gems (selenium-webdriver changes frequently in my experience)

**Closed by mattwynne** 2015-01-01 08:19 UTC
