### ISSUE TITLE
Introduce "Step Declaration" File

### ISSUE THREAD

**Issue by haikalpribadi** [cucumber/cucumber#946] opened 2020-03-28 19:56 UTC
## Summary

Right now, you can define Feature Scenarios in the `.feature` file. However, by looking at only the Feature file, you are not able to tell what are the exhaustive list of available Steps to be used in every Scenario. To know the list of Steps, one must check the Step Definition source code, which could be located in a place where the tester is unfamiliar, or might not even be in the same repository (for multi-repo architectures, where multiple repositories depend on one Behavior definition repository). Not only this makes it hard for the person who writes the Feature definitions to know all the steps made available to them, it also removes any possibility in developing a compile-time or syntax-highlighter check if the Feature files are correct.

## Expected Behavior

For us to be able to: review/access a list of steps available for Feature definitions, build syntax highlighters, and check the correctness of Feature files at compile-time rather than runtime.

## Current Behavior

Right now, none of this is possible.

## Possible Solution

**Introduce "Step Declaration" File**

Ideally, we can "declare" Steps in a file, just like how we define Features. Imagine a `*.step` file, containing just the list of step regular expressions, and no implementation. A Feature file could then import multiple `*.step` files at the header, which opens up so many possibilities in terms of scoping, syntax highlighting, and compile-time checking.

## Context & Motivation

When you're working across multiple repositories, where many repos implement the Feature definitions in their tests, it's very useful to have a list of Steps that is agreed as "services" that a system provides. The writer and maintainer of the Feature files do not need to know where and how the Steps are defined - which could be at multiple repositories.

Think of it as an "interface to Step definitions". Just the list of steps the system(s) support, the syntax and parameters it expects, and nothing else. This could take Cucumber to the next level as a BDD framework for large codebases sitting across multiple repositories.

## Your Environment

* Link to your project: https://github.com/graknlabs
* We haven't made our BDD feature definition repository public

**Comment by aslakhellesoy** [comment] 2020-03-30 23:27
I'm closing this as it seems to be a duplicate of #521

**Closed by aslakhellesoy** 2020-03-30 23:27 UTC

**Comment by haikalpribadi** [comment] 2020-03-30 23:52
Issue #521 is exactly the same as the one I'm proposing, @aslakhellesoy. They are similar, yes. But not the same.

**Comment by haikalpribadi** [comment] 2020-03-31 07:31
Issue #521 is not exactly the same as the one I'm proposing, @aslakhellesoy. They are similar, yes. But not the same.

In this solution I'm proposing, the developer will be able to write and maintain the "Step Declaration" file as source code.
