### ISSUE TITLE
Integrated HTML reporter - Background steps should not be marked as skipped when the feature is a mix of passed and skipped scenarios

### ISSUE THREAD

**Issue by hdorgeval** [cucumber/cucumber#1291] opened 2021-01-02 10:10 UTC
This is just a feedback on the integrated HTML steps.
Below is a screenshot of the html report of a feature that contains passed and skipped scenarios:
You can notice that the background steps are marked as skipped, though they run successfully at least one time:

![Screen Shot 2021-01-02 at 11 05 30](https://user-images.githubusercontent.com/9698924/103455135-902f2880-4cea-11eb-96d7-ee29109f753f.png)

**Comment by davidjgoss** [comment] 2021-01-02 11:52
Seems like we could address by styling differently and colouring grey?

cc @aslakhellesoy

**Comment by aslakhellesoy** [comment] 2021-01-04 23:43
@hdorgeval what would you have preferred the status of the background step to be in this case?

What caused the Scenario Outline’s steps to be skipped in this case?

**Comment by luke-hill** [comment] 2021-01-05 10:59
This feels a bit intractable. Because the Background was scheduled to run twice. And for scenario 1 it ran and passed and I'm guessing by the tag. The entire scenario was skipped for scenario 2. Probably through the ignore tag. I appreciate the skipped moniker here is weird, but to me it feels kind of right. But I guess it's a tricky one to pin down.

Is it causing any issues with people reading the reports e.t.c. - Remembering that background steps are kind of meant to be "hidden" and not relevant to the actual story / test case @hdorgeval

**Comment by davidjgoss** [comment] 2021-01-05 11:14
@luke-hill yeah on reflection I agree. I think the current behaviour is consistent with what we do when e.g. one example in a scenario outline fails - we mark the step with the "worst" result.

**Comment by luke-hill** [comment] 2021-01-14 15:07
@hdorgeval Are you happy if we close this as - "Cannot reliably solve". I think the current approach is probably the best "shoe-fits" policy.

**Comment by hdorgeval** [comment] 2021-01-14 18:52
Hi @luke-hill , 

> background steps are kind of meant to be "hidden" and not relevant to the actual story / test case

My use of the background is to gather all steps that are common to all scenario. 

For example: 

```text
scenario: test 1
  step A
  step B
  step C

scenario: test2
  step A
  step B
  step F

scenario: test3
  step A
  step B
  step G
```

The above feature file will be refactored to:

```text
background
  step A
  step B

scenario: test 1
  step C

scenario: test2
  step F

scenario: test3
  step G
```

In this use case, background steps status is as important as step status inside each scenario.

In my point of view, as soon as one background step status is different from one scenario to another scenario, you should duplicate the background steps status to all scenario. 

If you want I can provide you a mockup of the final html file to show you how I see things.

Thanks for your time and your support

**Comment by hdorgeval** [comment] 2021-01-14 19:15
Hi @luke-hill , here is my mockup:

![Screen Shot 2021-01-14 at 20 14 36](https://user-images.githubusercontent.com/9698924/104637519-2ed16700-56a5-11eb-9607-1a4f5ada6a0c.png)

**Comment by luke-hill** [comment] 2021-01-15 09:44
That is kind of against the principles of cucumber. It's unlikely we'd introduce this as new functionality.

See https://cucumber.io/docs/gherkin/reference/#Background for more reference. Specifically that

> Don’t use Background to set up complicated states, unless that state is actually something the client needs to know.

Maybe given we have this new protobuf style formats, it might be down-the-line that these kind of things are easy to extend. But we're still in the infancy with the formatters (html/json e.t.c.). I also haven't had a lot of time as a committer here to dive into these in more detail and get better acquainted.

If you are really interested in the steps in a Background, I'd argue they're not background steps, they're common steps. The two are often used interchangeably. However we mention things such as "incidental detail" again in the docs.

I think what we have here is actually a feature request from yourself to have the ability in the current js protobuf formatter to treat background steps as non-background steps. Which is a fair request, but a bit different to the original OP.

**Comment by hdorgeval** [comment] 2021-01-15 12:08
Hi @luke-hill , thanks a lot for your feedback!
Now I fully understand your point of view. 

I just wonder if I am the only guy to use Background as a way to gather common steps. It would be great if you could open a poll on twitter or other media to ask users on that subject.

Thanks a lot for your great feedbacks and feel free to close this issue.

**Comment by luke-hill** [comment] 2021-01-15 12:51
If your mockup of your HTML report is something you desire, the way in which cucumber (In the latest versions), works is that we expose all the info as messages. So you could create your desired HTML report, I don't want you think that this isn't possible. Just ideally Background steps "shouldn't" matter.

Or put another way, Background steps "Shouldn't" ever fail, because it's just setting the system up to work, as an example.

```
Background:
  Given a person called Luke
```

This will never fail, because I am always going to be called Luke. e.t.c. This is also the reason we usually often indicate to have only `Given` steps or Pre-conditions as a background.

**Closed by luke-hill** 2021-01-15 12:51 UTC
Labels: language: javascript, library: cucumber-react, type: bug

**Comment by hdorgeval** [comment] 2021-01-15 13:16
@luke-hill, I already started to write a simple console formatter: [cucumber-console-formatter](https://github.com/hdorgeval/cucumber-console-formatter) to see how things work. Nevertheless, developing a custom HTML formatter is feasible but is a huge work, and I really appreciate the great work already done in the current HTML formatter.

Thanks again for your feedback 👍

**Comment by mpkorstanje** [comment] 2021-01-15 13:35
@luke-hill 

I do think this is purely a representation problem caused by trying to create a facsimile of the feature file rather then represent what is actually executed. Other reporting plugins don't do this and simply don't have this problem. And while we may wish that setup is simple and unable to fail, this is not guaranteed and should not be hidden in the report when it happens.

**Comment by mpkorstanje** [comment] 2021-01-15 13:36
@hdorgeval I'm not involved much with the html formatter but I do think that we could accept your proposal as PR. 

@aslakhellesoy @vincent-psarga what do you think?

**Comment by luke-hill** [comment] 2021-01-15 14:43
I think it's down to opinion @mpkorstanje as there are quite a few formatters that I know of that omit the background steps (Irrespective of pass/fail). I think what we need to do here is establish the next steps. Given the variations of consensus, maybe having this togglable. Or as mentioned possibly a side formatter could be developed if you want full customisation.

I would say the current state is valid (i.e. not buggy), and potentially the next steps would be a feature request or a collaborative session where we work out what should be next.

@hdorgeval the current guise formatter is less than a year old, so hopefully we can start building them up more. Luckily irrespective of your cucumber flavour, it will (or should), look the same now, so it's a lot easier to maintain.
