### ISSUE TITLE
Not displaying appropriate error message .

### ISSUE THREAD

**Issue by ShreyasPatil** [cucumber/cucumber#803] opened 2015-02-12 15:05 UTC
Steps to reproduce:

1. Open command prompt
2. Hit command <code>cucumber -f html -o result.html</code> or <code>cucumber --format html --out result.html</code> outside cucumber project directory.
3. Getting error ->  No such file or directory - ûf. Please create a ûf directory to get started. (Errno::ENOENT) .

<code>
H:\>cucumber -f html -o result.html
</code>
<code>
No such file or directory - ûf. Please create a ûf directory to get started. (Errno::ENOENT)
</code>

Note: Hit command cucumber outside cucumber project directory this will give Error -> No such file or directory - features. Please create a features directory to get started. (Errno::ENOENT). This error message gives appropriate idea about what went wrong.
<code>
H:\>cucumber
</code>
<code>
No such file or directory - features. Please create a features directory to get started. (Errno::ENOENT)
</code>

**Comment by mattwynne** [comment] 2015-02-12 15:08
I can't reproduce this.

Please can you tell us a bit more about your context? Are you on Windows? Which version? Which version of Ruby and Cucumber are you using?

**Comment by osteenbergen** [comment] 2015-02-13 09:16
I think I have an idea why its going wrong. The dash character is not the actual ```-``` but the ```û``` character that cucumber reports. 

From a CLI perspective this changes the ```-f``` parameter to an argument and cucumbers first argument is the folder containing the feature files.

The solution is to write a normal dash.

Google searching shows pages like:
http://stackoverflow.com/questions/5970935/using-en-dash-in-an-input-file-to-a-batch-file

**Comment by mattwynne** [comment] 2015-02-13 09:23
Thanks @osteenbergen - very helpful. I'm going to close this issue.

**Closed by mattwynne** 2015-02-13 09:23 UTC
