### ISSUE TITLE
cucumber-expressions: Cucumber treats a (?!text) group as a capturing group; IndexError is then thrown

### ISSUE THREAD

**Issue by madkin10** [cucumber/cucumber#481] opened 2018-09-20 18:19 UTC
## Summary
Given a step definition with a regexp that contains a negative look ahead and a capturing group back to back, causes cucumber to fail to load and gives an unhelpful error message "index 2 out of matches (IndexError)". This is the step definition:

```ruby
And(/^the Projected Answer Time shown in the response accounts for the timezone (?!offset)(.*)$/) do |timezone|
....
end
```

## Expected Behavior

This step definition worked with v2.4.0, it should still work or provide a more detailed error message that would help resolve the problem.

## Current Behavior

An index 2 out of matches (IndexError) error is raised:

~~~
index 2 out of matches (IndexError)
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/group_builder.rb:20:in `offset'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/group_builder.rb:20:in `build'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/group_builder.rb:19:in `block in build'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/group_builder.rb:19:in `map'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/group_builder.rb:19:in `build'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/tree_regexp.rb:51:in `match'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/argument.rb:10:in `build'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/regular_expression.rb:32:in `match'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/glue/step_definition.rb:101:in `arguments_from'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:66:in `block in step_matches'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:65:in `each'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:65:in `reduce'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/glue/registry_and_more.rb:65:in `step_matches'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/step_match_search.rb:19:in `call'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/step_match_search.rb:19:in `call'
/Users/madkins/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/delegate.rb:83:in `method_missing'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/step_match_search.rb:62:in `call'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:66:in `matches'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:47:in `result'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:37:in `find_match'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:33:in `attempt_to_activate'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:29:in `map'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:29:in `new_test_steps'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:23:in `test_case'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/filters/activate_steps.rb:12:in `test_case'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/locations_filter.rb:18:in `block in done'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `each'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `done'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/compiler.rb:24:in `done'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:32:in `parse'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:21:in `compile'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:74:in `run!'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
/Users/madkins/.rvm/gems/ruby-2.4.2/gems/cucumber-3.1.0/bin/cucumber:9:in `<top (required)>'
/Users/madkins/.rvm/gems/ruby-2.4.2/bin/cucumber:23:in `load'
/Users/madkins/.rvm/gems/ruby-2.4.2/bin/cucumber:23:in `<main>'
~~~

## Steps to Reproduce (for bugs)

1. Define the error raising step:
```ruby
And(/^foo is a (?!big)(.*)$/) do |bar|
  puts bar
end
```
2. Define an ambiguous step to show the need for this to work:
```ruby
And(/^foo is a big (.*)$/) do |bar|
  puts bar
end
```
3. Define 2 scenarios that utilize the steps:
```gherkin
  Scenario: Cucumber fails to load
    Given foo is a bar
    
  Scenario: Used to prevent ambiguous steps
    Given foo is a big bar
```
4. Run the tests: `bundle exec cucumber`

## Your Environment

* Version used: 3.10
* Operating System and version: MacOS High Sierra 10.13.3

## Related Issue: https://github.com/cucumber/cucumber/issues/329

**Comment by luke-hill** [comment] 2019-01-29 10:46
@madkin10 - I'm not sure this is a bug because your non-capturing group should be defined using `?:`

Could you please check your input values, and try using `?:` and report back with findings?

**Comment by nzifnab** [comment] 2019-02-28 23:21
Using `(?!` is a [Negative Look-Ahead](https://www.regular-expressions.info/lookaround.html), as well as a non-capturing group.

I'm also getting this error when upgrading a legacy app where the step definition reads:

```
Then /^I should not see ([^"'](?:(?!within).)*)$/ do |obj|
  # blah
end
```

Where it's using that negative lookahead to say "The string should not contain 'within'"

For me this is failing on cucumber v 3.1.2

Reverting to cucumber 2.4.0 allowed the specs to run, so that's what I'll use for now.

**Comment by luke-hill** [comment] 2019-03-01 08:32
@nzifnab - Yes I'm aware, that's what I've posted. There is an issue here but the issue is slightly muddied by the fact the OP has posted a bug for one issue, but his Reproducible case shows another issue (Maybe by mistake)

Logically; I'm unable to see how this could be fixed in pseudo code nicely, let alone ruby, because 2 back-to-back captures, one of which is a negative lookahead and one of which is a greedy capture, should always capture the negative lookahead as `nil` and the greedy as the whole. But that's getting into another discussion.

**Comment by nzifnab** [comment] 2019-03-01 19:07
@luke-hill But a negative-lookahead isn't a "capture", it might be using parenthesis, but it doesn't populate back-references or capture matched characters.

Also since this works in `2.4.0`, this seems like a regression.

I think his usage of the phrase "non capturing group" in his summary is what's giving you pause. I don't think this happens with normal non-capturing groups `(?:regex)`, just look-arounds, and I'm not convinced they have to be back-to-back with actual captures; in my failing example the lookaround is inside the capturing group.

**Comment by madkin10** [comment] 2019-03-01 19:17
@nzifnab Is correct. My verbiage may have been a little off but either way it is a regression from the previous version.

**Comment by luke-hill** [comment] 2019-03-04 08:14
Ok ignore whether they are captured or not, it's still quite a lot of complex logic, because you have 2 potentially infinite groups.

Now obviously because the 2nd one is greedy, I "believe" the correct capture is for the first one to be nil. But is this what is intended?

There are a few other areas in the cucumber library (v3 onwards), where certain "possible" capture scenarios are ambiguous.

I agree the error is a bit ambiguous, I've tried to dive in a little bit but got a bit caught up and confused as I've been working on triaging a few bug issues recently.

**Comment by luke-hill** [comment] 2019-03-04 09:18
Update: After finding roughly where the code is crashing (Which in itself is tricky), I have nailed down the issue (Just not how to solve it)

At the point where cucumber creates CukeExp GroupBuilders; the `?!` group is being captured.

I believe at some point all groups which are classified as non-capturing get deleted and sanitized out. Unfortunately, this one is being referred to as capturing. Then it has some issue.

If we can find out where it is creating the raw group and find out what logic determines whether to create a capturing group or not, it should be a trivial one line fix (The issue is I don't know where this would be)

I'm going to take a break from this for a week or so to try let me eyes refresh and see if anyone else has any thoughts.

Code debug dump below
```
@group_builders
=> [#<Cucumber::CucumberExpressions::GroupBuilder:0x0000556ffdfcdce0 @group_builders=[], @capturing=true, @source="?!big">, #<Cucumber::CucumberExpressions::GroupBuilder:0x0000556ffdfcd510 @group_builders=[], @capturing=true, @source=".*">]
```

**Comment by mpkorstanje** [comment] 2019-03-04 14:41
If it helps anybody Java captures/parses the regex in: https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/TreeRegexp.java#L23

**Comment by nzifnab** [comment] 2019-03-04 19:07
I'm not a Java guy, but good link @mpkorstanje 

In particular, this conditional looks like a potential culprit:  https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/java/src/main/java/io/cucumber/cucumberexpressions/TreeRegexp.java#L56

It should maybe be `:` or `!` or `=` to indicate the various kinds of lookaheads.  Might also need it to check for `<!` and `<=` for negative and positive lookbehinds.

Might look something like:

            } else if (c == '?' && last == '(') {
                nonCapturingMaybe = true;
            } else if ((c == ':' || c == '!' || c == '=') && nonCapturingMaybe && last == '?') {
                stack.peek().setNonCapturing();
                nonCapturingMaybe = false;
            } else if ((c == '!' || c == '=') && nonCapturingMaybe && last == '<') {
                stack.peek().setNonCapturing();
                nonCapturingMaybe = false;
            }

I could see adding an additional `else{ nonCapturingMaybe = false; }` at the end too, to prevent the edge case of a regex like:  `/foo(bar?:baz)/` from being thought of as a non-capturing group, when in fact it only has a capturing group, and will match a string like: `"fooba:baz"`

Because as it looks right now, seems like that could happen and it might flag it as non-capturing?.

**Comment by mpkorstanje** [comment] 2019-03-04 19:21
https://github.com/cucumber/cucumber/blob/master/cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/tree_regexp.rb

This would be the Ruby file.

**Comment by luke-hill** [comment] 2019-03-05 08:21
Yeh I found the ruby file (name / location same as java), just needing a few days off this ticket to try refocus.

If someone else wants to tackle it meanwhile, feel free (I've whacked a help wanted label on for that purpose)

**Comment by benariss** [comment] 2019-06-14 09:24
I'm also running into this problem with both negative and positive lookarounds being flagged as capturing groups by Cucumber, but not included in the groupCount() value leading to a NoSuchElement exception from the mismatch in groups.
The fix in #593 looks to have fixed this for negatives but not positive lookaheads ('(?=...)'), or look behinds ('(?<=..)' and '(?<!...)').

**Comment by luke-hill** [comment] 2019-06-20 10:31
@benariss given the complexities of fixing it in multiple languages I think we're going to get it merged in as is, have you use the newly cut branch/es and then raise a new issue so we don't over-cloud the issue.

A lot of additional work standardising the tests was done which needs to be maintained going forwards.

**Comment by benariss** [comment] 2019-06-25 09:58
@luke-hill Thanks Luke, issue #643 raised for the remaining lookarounds.

**Closed** 2019-06-27 13:58 UTC
Labels: Slow Burner, language: ruby, library: cucumber-expressions, type: bug
