### ISSUE TITLE
Steps with percent sign cause cucumber to crash

### ISSUE THREAD

**Issue by dabroz** [cucumber/cucumber#276] opened 2017-10-04 15:38 UTC
## Faulting feature file

```
Feature: Foo

Scenario: Bar
  Given I am 20% foobar
```

## Expected Behavior

Generate step placeholder, ideally with `20%` parsed as an expression:

```
Given("I am {int}% foobar") do |int|
  pending # Write code here that turns the phrase above into concrete actions
end
```

It should not crash.

## Current Behavior

```
too few arguments (ArgumentError)
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/generated_expression.rb:11:in `sprintf'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/generated_expression.rb:11:in `source'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:94:in `block in to_s'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `each'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `each_with_index'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `each'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `map'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `to_s'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:20:in `call'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/runtime_facade.rb:17:in `block in snippet_text'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/runtime_facade.rb:16:in `map'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/runtime_facade.rb:16:in `snippet_text'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:131:in `block in print_snippets'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:138:in `block in do_print_snippets'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:137:in `map'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:137:in `do_print_snippets'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:133:in `print_snippets'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/pretty.rb:248:in `print_summary'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/pretty.rb:44:in `after_features'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/ignore_missing_messages.rb:11:in `method_missing'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:136:in `after'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:41:in `block in initialize'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/configuration.rb:32:in `notify'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:75:in `run!'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
/Users/username/.rvm/gems/ruby-2.3.1/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
/Users/username/.rvm/gems/ruby-2.3.1/bin/cucumber:22:in `load'
/Users/username/.rvm/gems/ruby-2.3.1/bin/cucumber:22:in `<main>'
/Users/username/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/username/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

## Your Environment

```
$ cucumber --version
3.0.1

$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
```

**Comment by KFairns** [comment] 2017-10-04 16:52
I cannot reproduce this error with the step definition you used and the following versions:
``` 
cucumber 3.0.1 
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
```

**Comment by dabroz** [comment] 2017-10-04 17:27
Steps to reproduce with stock docker ruby:

```
$ docker run -it ruby:2.3 bash

root@f8eb0d388303:/# mkdir -p app/features/crash; cd app; gem install cucumber
Fetching: gherkin-4.1.3.gem (100%)
Successfully installed gherkin-4.1.3
Fetching: cucumber-tag_expressions-1.0.1.gem (100%)
Successfully installed cucumber-tag_expressions-1.0.1
Fetching: backports-3.8.0.gem (100%)
Successfully installed backports-3.8.0
Fetching: cucumber-core-3.0.0.gem (100%)
Successfully installed cucumber-core-3.0.0
Fetching: builder-3.2.3.gem (100%)
Successfully installed builder-3.2.3
Fetching: diff-lcs-1.3.gem (100%)
Successfully installed diff-lcs-1.3
Fetching: multi_json-1.12.2.gem (100%)
Successfully installed multi_json-1.12.2
Fetching: multi_test-0.1.2.gem (100%)
Successfully installed multi_test-0.1.2
Fetching: cucumber-wire-0.0.1.gem (100%)
Successfully installed cucumber-wire-0.0.1
Fetching: cucumber-expressions-4.0.3.gem (100%)
Successfully installed cucumber-expressions-4.0.3
Fetching: cucumber-3.0.1.gem (100%)
Successfully installed cucumber-3.0.1
11 gems installed

root@f8eb0d388303:/app# cucumber --version
3.0.1

root@f8eb0d388303:/app# ruby --version
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-linux]

root@f8eb0d388303:/app# cucumber --init
   exist   features
  create   features/step_definitions
  create   features/support
  create   features/support/env.rb

root@f8eb0d388303:/app# echo -e "Feature: Foo\n\nScenario: Bar\n  Given I am 20% foobar" > features/crash/crash.feature

root@f8eb0d388303:/app# cucumber
Feature: Foo

  Scenario: Bar           # features/crash/crash.feature:3
    Given I am 20% foobar # features/crash/crash.feature:4

1 scenario (1 undefined)
1 step (1 undefined)
0m0.008s
too few arguments (ArgumentError)
/usr/local/bundle/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/generated_expression.rb:11:in `sprintf'
/usr/local/bundle/gems/cucumber-expressions-4.0.3/lib/cucumber/cucumber_expressions/generated_expression.rb:11:in `source'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:94:in `block in to_s'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `each'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `each_with_index'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `each'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `map'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:92:in `to_s'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/glue/snippet.rb:20:in `call'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/runtime_facade.rb:17:in `block in snippet_text'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/runtime_facade.rb:16:in `map'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/runtime_facade.rb:16:in `snippet_text'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:131:in `block in print_snippets'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:138:in `block in do_print_snippets'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:137:in `map'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:137:in `do_print_snippets'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/console.rb:133:in `print_snippets'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/pretty.rb:248:in `print_summary'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/pretty.rb:44:in `after_features'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/ignore_missing_messages.rb:11:in `method_missing'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:136:in `after'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/formatter/legacy_api/adapter.rb:41:in `block in initialize'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:34:in `each'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/usr/local/bundle/gems/cucumber-core-3.0.0/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/configuration.rb:32:in `notify'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/runtime.rb:75:in `run!'
/usr/local/bundle/gems/cucumber-3.0.1/lib/cucumber/cli/main.rb:33:in `execute!'
/usr/local/bundle/gems/cucumber-3.0.1/bin/cucumber:9:in `<top (required)>'
/usr/local/bundle/bin/cucumber:23:in `load'
/usr/local/bundle/bin/cucumber:23:in `<main>'

root@f8eb0d388303:/app# 
```

**Comment by aslakhellesoy** [comment] 2017-10-05 14:04
Fixed by #279

**Closed by aslakhellesoy** 2017-10-05 14:04 UTC
Labels: language: ruby, library: cucumber-expressions

**Comment by aslakhellesoy** [comment] 2017-10-05 15:06
@dabroz can you upgrade to cucumber-expressions 4.0.4 and confirm whether that fixes it for you please?

**Comment by dabroz** [comment] 2017-10-05 19:13
@aslakhellesoy Yeah, it works fine now. Thanks for a quick fix.

My output now:

```
You can implement step definitions for undefined steps with these snippets:

Given("I am {int}% foobar") do |int|
  pending # Write code here that turns the phrase above into concrete actions
end
```
