### ISSUE TITLE
Gherkin-Windows-386.exe Detected as malware.

### ISSUE THREAD

**Issue by Weirdphish** [cucumber/cucumber#1149] opened 2020-08-18 11:28 UTC
GHERKIN

We've seen several instances of gherkin-windows-386.exe being pulled down by NodeJS which are getting detected as malicious specifically: Heur.AdvML.C.

The exe's SHA256 hash is: **b103a82ff0732b561b6d684f3450de62a78f24223746e64c918abeca7875d132**

Checking the package out on Virustotal shows 13 vendors view the file to be malicious: https://www.virustotal.com/gui/file/b103a82ff0732b561b6d684f3450de62a78f24223746e64c918abeca7875d132/detection

Sandbox analysis of the file also shows it to be malicious: https://www.hybrid-analysis.com/sample/b103a82ff0732b561b6d684f3450de62a78f24223746e64c918abeca7875d132?environmentId=100

The file hash is also flagged as malicious on Cisco Talos's site as well. 

I've downloaded the latest package cucumber-gherkin/v15.0.2/cucumber-gherkin-windows-386.exe from here: https://github.com/cucumber/cucumber/releases/download/cucumber-gherkin%2Fv15.0.2/cucumber-gherkin-windows-386.exe
Latest version SHA256 Hash: 35da49b0e1deebac7ecb780bd3ffb70b9be0628059f5286955e1c457b21490ae

This package is also detected as malicious.

This may well be a false positive, however I need more information. Are you able to confirm if the original hash provided matches that of one of your previous legitimate releases?

**Comment by aslakhellesoy** [comment] 2020-08-18 11:32
Dang! I thought this was fixed in [8.0.0](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md#800---2019-10-03) where we dropped the binary gherkin executables and restored the native JavaScript parser.

It sounds like we've forgotten to remove the binaries from the npm package. I'll look into this. Thanks for reporting this!

**Comment by Weirdphish** [comment] 2020-08-18 11:43
No problem. I take it from that the hashes match your package and we can treat this as a false positive?

Thanks.

**Comment by aslakhellesoy** [comment] 2020-08-18 15:43
I can confirm the exe file is not malware, it's a cross-compiled golang executable of https://github.com/cucumber/cucumber/tree/master/gherkin/go

I'm puzzled about this executable being pulled down by Node.js though. Can you point me to the code that's downloading it?

**Comment by aslakhellesoy** [comment] 2020-08-19 08:00
gherkin versions somewhere between 6.0.0 and 8.0.0 bundled cross-compiled Go executables that have since been removed. We decided to remove them for the exact same reason you're describing - they would trip up malware detectors.

The fix for your team would be to upgrade to a more recent Cucumber version that depends on later versions of gherkin that don't have these executables inside.

We still [release](https://github.com/cucumber/cucumber/releases) these executables as standalone executables, but they haven't been bundled inside the gherkin npm/gem/jar packages since 8.0.0.

If you *really* need to verify the checksums of the executables inside old gherkin npm modules against the standalone published executables I'm afraid you'll have to wade through the releases pages and find the one you're looking for, download it and compare checksums.

As I said above, I'm almost certain the malware alert is a false positive.

Sorry for the inconvenience!

**Closed by aslakhellesoy** 2020-08-19 08:00 UTC
Labels: library: gherkin, type: build
