### ISSUE TITLE
Gherkin: Javascript implementation not working with the latest version of c21e

### ISSUE THREAD

**Issue by Lukas-Kullmann** [cucumber/cucumber#634] opened 2019-06-12 14:23 UTC
When using Gherkin 6.0.17 (latest version as of now) with c21e@1.2.1, it will throw a runtime error:

```
ERROR TypeError: ExeFile is not a constructor
  at new Gherkin (node_modules/gherkin/dist/src/index.js:48:21) 
  at Object.fromPaths (node_modules/gherkin/dist/src/index.js
```

We already had this issue with users of our project: https://github.com/kiwigrid/gherkin-testcafe/issues/36

Please release a Bugfix version of cucumber that fixes the version of c21e to version 1.1.9 or do a major release of c21e and unpublish the minor releases with breaking changes.

**Comment by aslakhellesoy** [comment] 2019-06-12 20:32
Thanks for reporting this. Could you please share some code that will reproduce the error? We’ll be able to fix it quicker if you do.

**Comment by Lukas-Kullmann** [comment] 2019-06-13 07:22
Well, you run the example from the [readme](https://github.com/cucumber/cucumber/blob/master/gherkin/javascript/README.md) with a freshly installed gherkin package. You should verify that it installed c21e@2.1.1 (which it does by default if you install gherkin into an empty project).

You try to run it and get the following error:

```
$ node index.js
/node_modules/gherkin/dist/src/index.js:48
    this._exeFile = new ExeFile(`${gherkinGoDir}/gherkin-go-{{.OS}}-{{.Arch}}{{.Ext}}`);
                    ^

TypeError: ExeFile is not a constructor
    at new Gherkin (/node_modules/gherkin/dist/src/index.js:48:21)
    at Object.fromPaths (/node_modules/gherkin/dist/src/index.js:18:10)
    at Object.<anonymous> (/index.js:8:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)

```

**Comment by joscha** [comment] 2019-06-13 08:05
We have debugged into this and more information:

it turns out that our CI machines have the following:

<img width="247" alt="1__joscha_canvabox____dev_canva_web__zsh_" src="https://user-images.githubusercontent.com/188038/59414741-76c34480-8e05-11e9-8c0a-d58afaeb6425.png">

however an install shows:

<img width="329" alt="canva____dev_canva__-_____web_src_pages_home_account_settings_account_information_features_account_information_feature__canva_" src="https://user-images.githubusercontent.com/188038/59414755-7e82e900-8e05-11e9-8b84-03e7f2c5ba76.png">

which means that:

`https://s3.eu-west-2.amazonaws.com/io.cucumber/gherkin-go/6.0.17/gherkin-go-linux-x64` is missing.

This results in the above error: `ERROR TypeError: ExeFile is not a constructor`.

The fix needs to be made in two places:
1. The `linux-x64` binary needs to be added here: https://github.com/cucumber/gherkin-javascript/blob/master/scripts/s3-download#L19
2. It needs to be built (and I *think* the code has to be somewhere in https://github.com/cucumber/cucumber/tree/master/gherkin/go but I can't figure out where for the life of it. I am happy to generate the binary on one of our build agents and provide it if that helps, so at least we don't block people on this.


//cc @olebedev

**Comment by aslakhellesoy** [comment] 2019-06-13 09:48
Thanks for all those details @joscha - that's very helpful.

If you're able to ssh into the CI maching, could you try one more thing for me? Rename/copy `gherkin-go-linux-amd64` to `gherkin-go-linux-x64` - I think they might be compatible. Then try to kick off the build again and see if that works.

Knowing whether or not it does will help us make a better fix in the next release.

Thanks again
Aslak

**Comment by joscha** [comment] 2019-06-13 11:50
after renaming I still get the same error, however:
```
sudo mv gherkin-go-linux-amd64 gherkin-go-linux-x64

./gherkin-go-linux-x64 --help
Usage of ./gherkin-go-linux-x64:
  -default-dialect string
    	the default dialect (default "en")
  -dialects
    	print dialects as JSON
  -json
    	Print messages as JSON instead of protobuf
  -no-ast
    	Skip gherkin AST events
  -no-pickles
    	Skip gherkin Pickle events
  -no-source
    	Skip gherkin source events
  -version
    	print version
```
seems to show that they are indeed compatible, so I think maybe something else might be broken as well.

**Comment by joscha** [comment] 2019-06-13 11:57
I think the second missing part might be an incorrect es6 export:
```
node
> const c = require('c21e')
undefined
> c
{ default: [Function: ExeFile] }
```
and then:

```
> new c.default()
ExeFile {
  fileNamePattern: undefined,
  props: { os: 'linux', arch: 'x64' } }
> new c()
TypeError: c is not a constructor
```

 if we make this: https://github.com/cucumber/gherkin-javascript/blob/04cb45c57d5f5ffd474d570c171f63f5518ed764/src/index.ts#L3 a named import or a `import * as ExeFile from ...` then it will work (together with the binary duplication for x64).

**Comment by aslakhellesoy** [comment] 2019-06-13 13:56
I was wondering about the `TypeError: ExeFile` error, which does indeed seem like a different issue.

I believe I have everything I need to fix this now. I’m quite busy the next week but I’ll get to this as soon as I can!

Cheers
Aslak

**Comment by joscha** [comment] 2019-06-13 22:10
If you give a pointer maybe someone can help? Or can you do what @Lukas-Kullmann suggests and
> Please release a Bugfix version of cucumber that fixes the version of c21e to version 1.1.9 or do a major release of c21e and unpublish the minor releases with breaking changes.

?

**Comment by joscha** [comment] 2019-06-17 00:33
Tried downgrading c21e to 1.1.9, doesn't seem to make a difference. Tried downgrading to `gherkin@6.0.13` but getting the strangest babel errors:
```
sh: babel: command not found
```
and then after installing babel:

```
ReferenceError: Unknown plugin "@babel/transform-async-to-generator" specified in "/home/ubuntu/x/node_modules/gherkin/.babelrc" at 0, attempted to resolve relative to "/home/ubuntu/x/node_modules/gherkin"
```
which persists even after a `yarn add @babel/plugin-transform-async-to-generator`.

There currently seems to be no way to make this work on CI @aslakhellesoy, any chance to get a fast fix in?

**Comment by joscha** [comment] 2019-06-18 00:14
When I monkey-patch `node_modules/gherkin/dist/src/index.js` with:

```
let ExeFile = require('c21e');

ExeFile = ExeFile.default;
```
I can make it work - it will even select the binary correctly it seems. I am unsure however if the fix should be made in the `c21e` package (making `ExeFile` a named export) or in the importing `gherkin` package - @aslakhellesoy can you please advise?

**Comment by joscha** [comment] 2019-06-19 07:17
If you are blocked by this issue (like we are), you can add:
```json
  "resolutions": {
    "gherkin": "joscha/gherkin-javascript#joscha/fix-exefile-constructor"
  }
```

to your `package.json` file to unblock yourself.
It will pull a fork of c21e-javascript and gherkin-javascript (the exact changes found in https://github.com/cucumber/cucumber/pull/641 plus the dist file updates and binaries).

**Comment by joscha** [comment] 2019-06-25 02:05
@aslakhellesoy any chance to get some attention on this, please?

**Comment by aslakhellesoy** [comment] 2019-06-25 05:49
Please be patient. It will get merged in due course.

**Comment by Dbuggerx** [comment] 2019-06-29 17:16
Hey @aslakhellesoy, it would be appropriate to have an estimate don't you think? @joscha was very nice to investigate, discuss, fix, and even propose a **temporary** workaround for the problem. Would there be any reason for the delay?

**Comment by aslakhellesoy** [comment] 2019-06-29 23:11
Hi @Dbuggerx - I hope to get to this next week, but I can't promise anything. As for reason for delay - we're a small team and have lots of issues to tend to as well as other duties. It's simple queuing theory. Check out [little's law](https://en.wikipedia.org/wiki/Little%27s_law) for a mathematical explanation ;-)

I do appreciate the great investigation by @joscha - that will certainly bump it up forward in the queue, which should reduce the lead time.

**Closed** 2019-07-01 13:13 UTC
Labels: library: c21e, library: gherkin, type: bug

**Comment by Lukas-Kullmann** [comment] 2019-07-25 09:00
@aslakhellesoy is there any possibility that you release a bugfix release with this soon? This is very blocking!

**Comment by aslakhellesoy** [comment] 2019-07-25 22:03
I’m on annual leave until mid-Aug. Unless someone else does this in the meanwhile it will have to wait until I am back.

**Comment by joscha** [comment] 2019-07-25 22:45
Is there an explanation on how to do a new release? Do I need anything else but GitHub access? Is there another person that is part of the project that has done this before and could assist?

**Comment by aslakhellesoy** [comment] 2019-07-26 11:27
The process is described in [RELEASE_PROCESS.md](https://github.com/cucumber/cucumber/blob/master/RELEASE_PROCESS.md). Only a select few people hold the keys to perform the process.

@vincent-psarga is one of those people.

We’ve made some more changes to c21e since this issue was fixed, so I think perhaps a new Gherkin release will be required too.
