### ISSUE TITLE
Create Cucumber plugin causes no feature file executed

### ISSUE THREAD

**Issue by peterwkc85** [cucumber/cucumber#676] opened 2019-08-06 07:11 UTC
No feature file get exeucted

## Summary
I wrote a custom plugin to initialize chrome and firefox web driver causes no feature file been executed.

## Expected Behavior
Feature File executed
Chrome open and close
Firefox open and close

## Current Behavior
Feature File no executed
Chrome open but no close
Firefox open but no close

## Steps to Reproduce (for bugs)
Attach google drive code

## Your Environment
Version used: Cucumber 4.2
Operating System and version: MS Windows 10
Link to your project: https://drive.google.com/open?id=1ycwBNZi9st-dkmdDfKaBxqU2mLchRWfM

**Comment by peterwkc85** [comment] 2019-08-06 09:13
This is a strange issue/bug. Please help to resolve it.

**Comment by luke-hill** [comment] 2019-08-07 11:53
Hi there, a previous core maintainer has requested you attach additional information so we can reproduce the issue.

He also requested you explain the issue in a bit more detail. Your problem is very far reaching. Could you maybe illustrate some steps that someone would need to do.

Also on a personal note, a google drive doc link is a bit obfuscated. Could you maybe create a small repo I could pull down and run something like `cucumber` on?

I can't tell what language binding you are using. Furthermore, you are driving a browser it seems, could you maybe elaborate more on how you do that?

**Comment by peterwkc85** [comment] 2019-08-07 13:54
The issue is I create a custom plugin called MyEventListener. This function of this plugin is to initialize web driver session and closed it on test start and test finish event. Thus, it cause no feature file been executed. 
I'm using Cucumber-JVM Java. 

Here is the repository: https://github.com/peterwkc85/Cucumber_4.1-AF

**Comment by peterwkc85** [comment] 2019-08-09 04:13
Please fix this bug...

**Comment by mpkorstanje** [comment] 2019-08-09 07:40
Please bear in mind that all contributors are volunteers, if you need in depth help with debugging consider reaching out to a coworker first. 

Now I previously asked you to follow these instructions: [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example).

However the example you have provided is neither minimal nor reproducible. At a glance it contains more then one feature file, more application code then needed, and there are multiple plugins involved. More importantly you do not make it clear what the error is and why given the cause of the error you'd expect different behavior.

**Comment by aslakhellesoy** [comment] 2019-08-12 13:21
After cleaning this up a bit (removing generated files from git) I ran `mvn clean test`. 0 scenarios are reported to STDOUT.

When I ran `ParallelRunner` from IDEA I saw a stack trace I didn't see in the console:

```
java.lang.IllegalArgumentException: nodeName cannot be null or empty

	at com.aventstack.extentreports.ExtentTest.createNode(ExtentTest.java:142)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.createTestCase(ExtentCucumberAdapter.java:399)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.handleTestCaseStarted(ExtentCucumberAdapter.java:158)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter.access$100(ExtentCucumberAdapter.java:62)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$3.receive(ExtentCucumberAdapter.java:104)
	at com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter$3.receive(ExtentCucumberAdapter.java:101)
	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
	at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
	at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
	at cucumber.runner.ThreadLocalRunnerSupplier$SynchronizedEventBus.send(ThreadLocalRunnerSupplier.java:90)
	at cucumber.runner.ThreadLocalRunnerSupplier$LocalEventBus.send(ThreadLocalRunnerSupplier.java:63)
	at cucumber.runner.TestCase.run(TestCase.java:36)
	at cucumber.runner.Runner.runPickle(Runner.java:40)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:124)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:65)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:133)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Screenshot: 
<img width="1505" alt="Screenshot 2019-08-12 at 13 45 45" src="https://user-images.githubusercontent.com/1000/62865906-f25f4600-bd0f-11e9-8bfa-320d85745713.png">

The Extent framework appears to be throwing exceptions for unnamed scenarios (both of yours are unnamed). This exception is *not* reported to the console for some reason. It's not reported to any log files either. I'm inclined to blame JUnit and/or Surefire for this lack of logging.

I think we can fix this in Cucumber-JUnit though. We can follow the stack trace to `cucumber.api.junit.Cucumber` line `133`:

https://github.com/cucumber/cucumber-jvm/blob/227c025b8b88f992a2a563dfadd647aeaf46f531/junit/src/main/java/cucumber/api/junit/Cucumber.java#L133

You can make the scenarios pass by either:

* Adding a name to each scenario
* Removing `"com.aventstack.extentreports.cucumber.adapter.ExtentCucumberAdapter:",` from `ParallelRunner`

I tried to upgrade to Cucumber-JVM 4.7.1 while keeping the extent plugin to see if that would cause the error to be printed to STDOUT or a log file, but the extent plugin seems to be [stuck](https://search.maven.org/artifact/com.aventstack/extentreports-cucumber4-adapter/1.0.7/jar) on cucumber-jvm. The [4.0.1](https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md#401) release is about a year old. I see you upgraded to 4.1.1.

I think we should try/catch errors in the cucumber-junit reporter and forward them to the JUnit `RunNotifier`. If we were to fix this in a future release you wouldn't be able to use the extent plugin since it doesn't seem to work with the latest version (4.7.1).

**Comment by aslakhellesoy** [comment] 2019-08-12 13:22
@mpkorstanje I suggest we close this issue and create a new one in cucumber-jvm: "Forward runtime exceptions to RunNotifier". WDYT?

**Comment by mpkorstanje** [comment] 2019-08-12 15:58
Thanks for looking into the deets Aslak. Coincidentally I fixed this in v5 https://github.com/cucumber/cucumber-jvm/commit/0e41a1a40248adb2a5307857fe751813d99c9809#diff-23e0f0b1f858161b842ad77bc9372185R71. So we can close this. 

And maybe report the problem to Aventstack.

**Comment by aslakhellesoy** [comment] 2019-08-12 16:17
Thanks @mpkorstanje. I'm closing this then. v5 will report misbehaving plugins better.

@peterwkc85 - the problem seems to be with the extend reporter, not your own plugin.

**Closed by aslakhellesoy** 2019-08-12 16:17 UTC

**Comment by peterwkc85** [comment] 2019-08-13 14:39
How to solve this issue?

**Comment by aslakhellesoy** [comment] 2019-08-13 15:56
> How to add name to each scenario?

Change `Scenario:` to `Scenario: something`. Or stop using the extent plugin, which throws errors when scenarios are not named.

**Comment by peterwkc85** [comment] 2019-08-14 03:32
Thanks a lot.
