### ISSUE TITLE
The `rule_type` parameter in 

### ISSUE THREAD

**Issue by drhuffman12** [cucumber/cucumber#207] opened 2017-05-12 00:40 UTC
`lib/gherkin/ast_builder.rb`
```rb
    def end_rule(rule_type)
      node = @stack.pop
      current_node.add(node.rule_type, transform_node(node))
    end
```

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by aslakhellesoy** [comment] 2017-07-20 13:55
Dupe of #208

**Closed by aslakhellesoy** 2017-07-20 13:55 UTC
